// @ts-check

/**
 * Sidebar for the standalone "API Reference" docs instance (public PHP functions +
 * hooks). Autogenerated from the reference/ folder, ordered by each page's
 * sidebar_position / _category_.json position.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  referenceSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
