// @ts-check

/**
 * Sidebar for the standalone "Guides" docs instance (its own left panel,
 * separate from the Manual). Autogenerated from the guides/ folder.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  guidesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
