// @ts-check

/**
 * The Unyson+ manual sidebar is generated automatically from the docs/ folder
 * structure (folders become categories via their _category_.json files).
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  // Focused, top-level "Extensions" sidebar — same docs instance, same
  // /docs/extensions/… URLs, just surfaced as its own navbar entry.
  extensionsSidebar: [{type: 'autogenerated', dirName: 'extensions'}],
};

export default sidebars;
