// @ts-check

/**
 * Sidebar for the standalone "AI Dev Kit" docs instance (its own left panel,
 * separate from the Manual). Autogenerated from the ai-dev-kit/ folder, ordered
 * by each page's sidebar_position.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  aiDevKitSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
