// @ts-check

/**
 * Sidebar for the standalone "The Theme" docs instance (its own left panel,
 * separate from the Manual). Autogenerated from the theme/ folder.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  themeSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
