// @ts-check

/**
 * Sidebar for the standalone "Animation Engine" docs instance (its own left
 * panel, separate from the Manual). Autogenerated from the animation-engine/
 * folder — the Scroll Motion (GSAP) pages live in the scroll-motion/ subfolder.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  animationEngineSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
