// @ts-check

/**
 * Sidebar for the standalone "Web Dev Basics" learning section (route /learn).
 * Autogenerated from the learn/ folder — a short, beginner-friendly primer on
 * building websites the right way, that the inline "💡 Web dev tip" callouts
 * across the docs link into.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  learnSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
