// @ts-check

/**
 * Sidebar for the standalone "Blocks" docs instance (its own left panel,
 * separate from the Manual). Autogenerated from the blocks/ folder — it covers
 * how Unyson+ works with the WordPress block editor, plus the roadmap that
 * tracks each phase as it lands.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  blocksSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
